spring.application.name: onboarding
spring:
  datasource:
    url: jdbc:h2:mem:onboarding;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: admin
  filter:
    create: All tasks
  database:
    type: h2

